version: "3"

services:
  db:
    container_name: postgresql_v2
    image: postgres:16-alpine
  
    environment:
      - POSTGRES_DB=orders
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5440:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - nats
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
       interval: 5s
       timeout: 5s
       retries: 5
    
      

  nats-streaming:
    container_name: nats-streaming_v2
    image: nats-streaming
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"
    depends_on:
      - db
    networks:
      - nats
    restart: always
    command: [
        '-p',
        '4222',
        '-m',
        '8222',
        '-hbi',
        '5s',
        '-hbt',
        '5s',
        '-hbf',
        '2',
        '-SD',
        '-cid',
        'test-cluster',
    ]
    

    
      
  # publisher:

  #   networks: 
  #     - dev
  #   build: 
  #     context: .
  #   depends_on:
  #     - nats-streaming
    

  # subscriber:

  #   networks: 
  #     - dev
  #   build: 
  #     context: .
  #   depends_on:
  #     - nats-streaming

      
networks:
  nats:
    name: nats
    driver: bridge

volumes:
  postgres:
    name: postgresql-nats-db
